---
rails__deploy_user: kotovalexarian
rails__user: partynest
rails__group: partynest
rails__root_dir: '/opt/partynest'
rails__service: partynest
rails__rvm: '/usr/local/rvm/bin/rvm'
rails__ruby: ruby-2.7.0
rails__gemset: partynest
rails__env: staging

rails__env_vars:
  POSTGRES_POOL: 5
  POSTGRES_HOST: 'private-db-postgresql-ams3-63609-do-user-4455684-0.db.ondigitalocean.com'
  POSTGRES_PORT: 25060
  POSTGRES_USER: 'partynest'
  POSTGRES_DB: 'partynest_staging'
  POSTGRES_PASSWORD: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    64643035646436663161646136626366353835333763653236616233333637313162333837393833
    3963306331386533346533363461356436316132373565380a656336353431336238646230343366
    38316637623465626636333837306665656538393536666237323763633963653166663135393038
    3035653831623931640a303838343266343462626330633530393562623061303436323738313064
    30393564393132626235386661343138373836333239356639656339333664333164

rvm1_rvm_version: stable
rvm1_rvm_check_for_updates: true
rvm1_install_path: '/usr/local/rvm'
rvm1_install_flags: '--auto-dotfiles'
rvm1_user: root
rvm1_rubies: ['ruby-2.7.0']
rvm1_bundler_install: false

partynest__redis_db_cache: 11
partynest__redis_db_sidekiq: 10

partynest__redis_host: private-db-redis-ams3-76837-do-user-4455684-0.db.ondigitalocean.com
partynest__redis_port: 25061

partynest__smtp_host: smtp.sendgrid.net
partynest__smtp_port: 587
partynest__smtp_user: apikey

partynest__recaptcha_site_key: '6LfqvL0UAAAAAJ28mP5C8zBQkXiYsYQwy3ZkLbuO'

partynest__redis_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35616230333138663335356133333038383633313133396537663131613861303537336134303862
  3731383464343236313535326238323231656634653132350a373136623732316237613662636466
  64333033663062313632626535316462383861303035383662323132613637353032666631323038
  6438613561613664620a653737366161663031323134303635376664643038363230633832356331
  38353231333365383533363262343335303264386663366531313636356431343635

partynest__smtp_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36623635626135366434623239636238356363303832646366643937646664363966313266623462
  3731613430313332636534393165343765633530386431390a633939656338366536376430356164
  30393862333933613839633033373635313937373532366366393665323865396431343732613932
  6131316431643033380a323033353664396461633436626637633339306537656261326232333566
  36343264613463643365353163616137623564613533356439373032663235633463646232633065
  64313265363437346530666439343030656362393730633962386235336133306638353065326139
  65386531643135366634613363626135646235356534316538323033666438316461366266663162
  31316138366536383535

partynest__recaptcha_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64383436656331646164643235356363656437323033313937393661643466383365313836366531
  3964306261313536353066306463656662373035346135660a646238383261386661333131343631
  35363865396638653831666532383566383138333836633131353536313133363934373439383030
  3437306638303637630a363266623830643433346637306361386533313135376639656563333237
  33663035653234393061333532653865373334373839346531353766326133336235383733316463
  6364363337666239366231656563376462623663303630363238
