---
partynest__deploy_user: kotovalexarian
partynest__domain: stg.libertarian-party.com
partynest__env: staging

partynest__pg_db: partynest_staging
partynest__pg_host: private-db-postgresql-ams3-63609-do-user-4455684-0.db.ondigitalocean.com
partynest__pg_port: 25060

partynest__redis_db_cache: 11
partynest__redis_db_sidekiq: 10

partynest__redis_host: private-db-redis-ams3-76837-do-user-4455684-0.db.ondigitalocean.com
partynest__redis_port: 25061

partynest__recaptcha_site_key: '6LfLa4EUAAAAADUTFj2GdnRh49kH_WBfUHabv8_7'

partynest__recaptcha_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30633235626661643538643938383735366265663133613038376138303961346239366332326139
  3932326462396533353166333430643235616131623935380a363733376331613661346537303438
  65633138333264316335633332656338623530363166306434373030643833333131363039393662
  3830323163363565310a613563353533373265343238366532396335303039613038636535316366
  37333066323639376335326630376533666662613766353837363739623238376538626537626463
  3833333737333536333965623536346164343533373264396265

partynest__redis_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35616230333138663335356133333038383633313133396537663131613861303537336134303862
  3731383464343236313535326238323231656634653132350a373136623732316237613662636466
  64333033663062313632626535316462383861303035383662323132613637353032666631323038
  6438613561613664620a653737366161663031323134303635376664643038363230633832356331
  38353231333365383533363262343335303264386663366531313636356431343635
