---
- name: Install Nginx
  apt:
    update_cache: true
    name: nginx

- name: Create directories for Nginx configuration
  file:
    state: directory
    path: '{{ item }}'
    mode: 'u=rwx,g=rx,o=rx'
    owner: root
    group: root
  with_items:
    - '/etc/nginx'
    - '/etc/nginx/sites-available'
    - '/etc/nginx/sites-enabled'

- name: Remove Nginx default site
  file:
    state: absent
    path: '/etc/nginx/sites-enabled/default'
  when: nginx__remove_default | bool
  notify: Restart Nginx

- name: Add Nginx sites
  template:
    src: 'templates/{{ item.type }}.conf'
    dest: '/etc/nginx/sites-available/{{ item.domain }}.conf'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  with_items: '{{ nginx__sites }}'
  notify: Restart Nginx

- name: Enable Nginx sites
  file:
    state: link
    src: '/etc/nginx/sites-available/{{ item.domain }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ item.domain }}.conf'
    owner: root
    group: root
  with_items: '{{ nginx__sites }}'
  notify: Restart Nginx
