---
- name: Create system group
  group:
    name: partynest
    system: true

- name: Create system user
  user:
    name: partynest
    group: partynest
    system: true
    create_home: false

- name: Install system packages
  apt:
    update_cache: true
    name:
      - build-essential
      - gnupg2
      - liblzma-dev
      - libpq-dev
      - patch
      - zlib1g-dev

- name: Create application directories
  file:
    state: directory
    path: '{{ item }}'
    mode: 'u=rwx,g=rwx,o=rx'
    owner: partynest
    group: partynest
  with_items:
    - '/opt/partynest'
    - '/opt/partynest/shared'
    - '/opt/partynest/shared/config'
