---
- name: Harden SSH daemon
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  notify:
    - Restart SSH daemon
  with_items:
    - regexp: '^#?PermitRootLogin '
      line:   'PermitRootLogin no'
    - regexp: '^#?MaxAuthTries '
      line:   'MaxAuthTries 2'
    - regexp: '^#?MaxSessions '
      line:   'MaxSessions 5'
    - regexp: '^#?PasswordAuthentication '
      line:   'PasswordAuthentication no'
    - regexp: '^#?ChallengeResponseAuthentication '
      line:   'ChallengeResponseAuthentication no'
    - regexp: '^#?AllowAgentForwarding '
      line:   'AllowAgentForwarding no'
    - regexp: '^#?AllowTcpForwarding '
      line:   'AllowTcpForwarding no'
    - regexp: '^#?X11Forwarding '
      line:   'X11Forwarding no'
    - regexp: '^#?TCPKeepAlive '
      line:   'TCPKeepAlive no'
    - regexp: '^#?UseDNS '
      line:   'UseDNS no'

- name: Install useful packages
  apt:
    update_cache: true
    name: ['bash-completion', 'colordiff', 'curl', 'less', 'vim']

- name: Set Vim as default editor
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

- name: Install Vim config
  copy:
    src: files/vimrc.local
    dest: /etc/vim/vimrc.local
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root

- name: Add Certbot APT repository
  copy:
    src: files/certbot.list
    dest: /etc/apt/sources.list.d/certbot.list
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root

- name: Install Certbot
  apt:
    update_cache: true
    name: certbot

- name: Create directory for Let's Encrypt configuration
  file:
    state: directory
    path: '/etc/letsencrypt'
    mode: 'u=rwx,g=rx,o=rx'
    owner: root
    group: root

- name: Install Let's Encrypt config
  copy:
    src: files/letsencrypt-cli.ini
    dest: /etc/letsencrypt/cli.ini
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root

- name: Install Nginx
  apt:
    update_cache: true
    name: nginx

- name: Obtain Let's Encrypt certificate
  command: 'certbot certonly'
  register: certbot_result
  changed_when: "certbot_result.stdout is not search('Certificate not yet due for renewal; no action taken.')"

- name: Create directory for Nginx configuration
  file:
    state: directory
    path: '/etc/nginx'
    mode: 'u=rwx,g=rx,o=rx'
    owner: root
    group: root

- name: Create directory for Nginx certificates
  file:
    state: directory
    path: '/etc/nginx/certs'
    mode: 'u=rwx,g=rx,o=rx'
    owner: root
    group: root

- name: Download CloudFlare client certificate
  get_url:
    url: 'https://support.cloudflare.com/hc/en-us/article_attachments/201243967/origin-pull-ca.pem'
    checksum: 'sha256:c07f93a4866af4b14367b207f54154ea05629e52db8e333cc814fdec03ca3cf7'
    dest: '/etc/nginx/certs/cloudflare-origin-pull-ca.pem'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
