---
ansible_python_interpreter: /usr/bin/python3
certbot__email: 'kotovalexarian@gmail.com'
certbot__post_hook: 'systemctl is-active nginx.service || systemctl start nginx.service'
certbot__pre_hook:  'systemctl is-active nginx.service && systemctl stop  nginx.service'
