---
rails__deploy_user: kotovalexarian
rails__user: partynest
rails__group: partynest
rails__root_dir: '/opt/partynest'
rails__service: partynest
rails__rvm: '/usr/local/rvm/bin/rvm'
rails__ruby: ruby-2.7.0
rails__gemset: partynest
rails__env: production

rails__master_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34343836323931653630363632343165656462333534356563393765613835386661346236346339
  6662646535363230356630396632366661313434623663640a326662653463666334303732663636
  36613765363738363866373132343335303939383866363366306463303361343332346331383032
  3533323765356362320a633334383432663933346165346465663963613363363065336438623338
  66626131343430623738646262646139663263613634333635356163363537636265643364653035
  6438396238323263363136356136336436366134336130343838

rails__env_vars:
  POSTGRES_POOL: 5
  POSTGRES_HOST: 'private-db-postgresql-lon1-10864-do-user-4455684-0.db.ondigitalocean.com'
  POSTGRES_PORT: 25060
  POSTGRES_USER: 'doadmin'
  POSTGRES_DB: 'partynest_production'
  POSTGRES_PASSWORD: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32626164316262373139333463386433346565323438396662306337666562636238656331376163
    6430623565653138396337653333633261613863333364310a333263376339356135373965303739
    31376666373530376461663064323635663836663631386162316263646530323564326463636138
    6363666531626364660a353038666664313039353965326634633738386433643638633063616630
    30393463363364306661623962636365326364373163336430613364313530653339

rvm1_rvm_version: stable
rvm1_rvm_check_for_updates: true
rvm1_install_path: '/usr/local/rvm'
rvm1_install_flags: '--auto-dotfiles'
rvm1_user: root
rvm1_rubies: ['ruby-2.7.0']
rvm1_bundler_install: false

partynest__redis_db_cache: 1
partynest__redis_db_sidekiq: 0

partynest__redis_host: private-db-redis-ams3-76837-do-user-4455684-0.db.ondigitalocean.com
partynest__redis_port: 25061

partynest__smtp_host: smtp.sendgrid.net
partynest__smtp_port: 587
partynest__smtp_user: apikey

partynest__recaptcha_site_key: '6LfLa4EUAAAAADUTFj2GdnRh49kH_WBfUHabv8_7'

partynest__redis_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35616230333138663335356133333038383633313133396537663131613861303537336134303862
  3731383464343236313535326238323231656634653132350a373136623732316237613662636466
  64333033663062313632626535316462383861303035383662323132613637353032666631323038
  6438613561613664620a653737366161663031323134303635376664643038363230633832356331
  38353231333365383533363262343335303264386663366531313636356431343635

partynest__smtp_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36623635626135366434623239636238356363303832646366643937646664363966313266623462
  3731613430313332636534393165343765633530386431390a633939656338366536376430356164
  30393862333933613839633033373635313937373532366366393665323865396431343732613932
  6131316431643033380a323033353664396461633436626637633339306537656261326232333566
  36343264613463643365353163616137623564613533356439373032663235633463646232633065
  64313265363437346530666439343030656362393730633962386235336133306638353065326139
  65386531643135366634613363626135646235356534316538323033666438316461366266663162
  31316138366536383535

partynest__recaptcha_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30633235626661643538643938383735366265663133613038376138303961346239366332326139
  3932326462396533353166333430643235616131623935380a363733376331613661346537303438
  65633138333264316335633332656338623530363166306434373030643833333131363039393662
  3830323163363565310a613563353533373265343238366532396335303039613038636535316366
  37333066323639376335326630376533666662613766353837363739623238376538626537626463
  3833333737333536333965623536346164343533373264396265
