---
ansible_become_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31623137383461303734653331303231623830646165666536386530306464333235636334633439
  6637343962663761393561313639653636353036616334620a353664393936383532363436313831
  65323537623062616563326366626334363535386538633066653433643637356565333034666234
  3562363431653763620a393735653361653331333164663839376136643430386634356135636164
  36613538623838343763343063343632623739656331326632366264323838326665343637366331
  39663434366365663138663464656562373064663136613230643431626530666637653262313765
  65343466363833373764303931656137636234663531643164646535333766666138396265646536
  65363836633063393039

common__certbot__cert_name: 'beta.libertarian-party.com'
common__certbot__cert_domains:
  - 'beta.libertarian-party.com'

common__nginx__upstreams:
  - name: partynest
    servers: ['unix:/opt/partynest/shared/tmp/sockets/puma.sock']

common__nginx__sites:
  - type:     origin
    domain:   'beta.libertarian-party.com'
    cert:     '/etc/letsencrypt/live/beta.libertarian-party.com/fullchain.pem'
    key:      '/etc/letsencrypt/live/beta.libertarian-party.com/privkey.pem'
    ssl_conf: '/etc/letsencrypt/options-ssl-nginx.conf'
    root:     '/opt/partynest/shared/public'
    upstream: partynest
    external: false
