---
public_iface:  eth0
private_iface: eth1

public_ipv4_address: 167.99.254.23
public_ipv4_gateway: 167.99.240.1
public_ipv4_cidrlen: 20
public_ipv4_netmask: 255.255.240.0

public_ipv6_address: 2a03:b0c0:3:d0::5f64:1001
public_ipv6_gateway: 2a03:b0c0:3:d0::1
public_ipv6_cidrlen: 124
public_ipv6_from:    2a03:b0c0:3:d0::5f64:1000
public_ipv6_to:      2a03:b0c0:3:d0::5f64:100f

private_ipv4_address: 10.135.222.143
private_ipv4_cidrlen: 16
private_ipv4_netmask: 255.255.0.0

postgresql_host: localhost
postgresql_user: partynest_staff

redis__requirepass: 'c06ef8526383e8e752f069d32f258e4d'

certbot__email: 'kotovalexarian@gmail.com'
certbot__cert_name: 'staff.libertarian-party.com'
certbot__cert_domains:
  - 'staff.libertarian-party.com'

nginx__domain: 'staff.libertarian-party.com'
nginx__socket: '/opt/partynest/shared/tmp/sockets/puma.sock'
