---
- hosts: all
  roles:
    - role: ../roles/common
      tags: [common]
    - role: ../roles/certbot
      tags: [certbot]
    - role: ../roles/nginx
      tags: [nginx]
    - role: ../roles/redis
      tags: [redis]
    - role: ../roles/postgresql
      tags: [postgresql]
